import { Data, IProductInput } from '@/types'
import { toSlug } from './utils'

const products: IProductInput[] = [
  // Birthday Cakes
  {
    name: 'Black Forest Cake Half kg',
    slug: toSlug('Black Forest Cake Half kg'),
    category: 'Birthday-Cakes',
    images: ['/images/A1.jpg'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 499,
    listPrice: 0,
    flavour: 'Chocolate',
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 9,
    countInStock: 11,
    description:
      'Moist chocolate sponge layered with fresh cream and juicy cherries, topped with chocolate shavings — a timeless classic for any celebration.',
    sizes: ['1/2-Kg'],
    shapes: ['Round'],

    reviews: [],
  },
  {
    name: 'Cream Drop Chocolate Cake Half kg',
    slug: toSlug('Cream Drop Chocolate Cake Half kg'),
    category: 'Birthday-Cakes',
    images: ['/images/A2.jpg'],
    tags: ['featured'],
    isPublished: true,
    price: 549,
    listPrice: 0,
    flavour: 'Chocolate',
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 29,
    countInStock: 12,
    description:
      'Satisfy your sweet cravings with this decadent half-kg Cream Drop Chocolate Cake, featuring soft, rich chocolate sponge layers generously coated with silky chocolate cream. Topped with elegant cream drops and chocolate garnishes, it’s a perfect blend of texture and taste — ideal for small celebrations or a cozy indulgence.',

    sizes: ['1/2-Kg'],
    shapes: ['Round'],

    reviews: [],
  },
  {
    name: 'Butterscotch Bliss Cream Cake',
    slug: toSlug('Butterscotch Bliss Cream Cake'),
    category: 'Birthday-Cakes',
    flavour: 'Butterscotch',
    images: ['/images/A3.jpg'],
    tags: ['best-seller'],
    isPublished: true,
    price: 449,
    listPrice: 0,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 55,
    countInStock: 13,
    description:
      'Experience pure indulgence with our Butterscotch Bliss Cream Cake — a delightful fusion of soft vanilla sponge, rich butterscotch cream, and crunchy caramel bits. Each layer is generously frosted and finished with a golden glaze, creating a perfect balance of sweetness and texture.',
    sizes: ['1/2-Kg'],
    shapes: ['Heart'],

    reviews: [],
  },
  {
    name: 'Kit Kat Cake Half kg',
    slug: toSlug('Kit Kat Cake Half kg'),
    category: 'Birthday-Cakes',
    flavour: 'Chocolate',
    images: ['/images/A4.jpg'],
    tags: ['todays-deal'],
    isPublished: true,
    price: 699,
    listPrice: 0,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 54,
    countInStock: 14,
    description:
      'A chocolate lover’s dream come true! Our KitKat Cake features layers of moist chocolate sponge enveloped in rich chocolate cream, surrounded by crispy KitKat bars and topped with a generous crown of colorful gems or choco chips. Perfect for birthdays and celebrations, it’s a cake that’s as fun as it is delicious. ',
    sizes: ['1/2-Kg'],
    shapes: ['Round'],

    reviews: [],
  },
  //Anniversary Cakes
  {
    name: 'Anniversary Butterscotch Cake',
    slug: toSlug('Anniversary Butterscotch Cake'),
    category: 'Anniversay-Cakes',
    flavour: 'Butterscotch',
    images: ['/images/B1.jpg'],
    tags: ['new-arrival', 'featured'],
    isPublished: true,
    price: 599,
    listPrice: 0,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 54,
    countInStock: 15,
    description:
      'Celebrate love with our Anniversary Butterscotch Cake. A luxurious blend of soft, moist cake layers filled with rich butterscotch cream and topped with a delightful crunch of butterscotch pieces. The perfect sweet treat to make your special day even more memorable.',
    sizes: ['1/2-Kg'],
    shapes: ['Round'],

    reviews: [],
  },
  {
    name: 'Heart Red Velvet Cake',
    slug: toSlug('Heart Red Velvet Cake'),
    category: 'Anniversay-Cakes',
    flavour: 'Red Velvet',
    images: ['/images/B2.jpg'],
    tags: ['best-seller', 'todays-deal'],
    isPublished: true,
    price: 799,
    listPrice: 0,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 16,
    numSales: 56,
    description:
      'Make your occasion extra special with our Heart Red Velvet Cake. This stunning cake features a soft, velvety red sponge paired with a smooth cream cheese frosting. Its rich flavor and eye-catching heart shape make it the perfect expression of love and celebration.',
    sizes: ['1/2-Kg'],
    shapes: ['Heart'],

    reviews: [],
  },
  //Designer Cakes
  {
    name: 'Floral Designer Chocolate Cake',
    slug: toSlug('Floral Designer Chocolate Cake'),
    category: 'Designer-Cakes',
    flavour: 'Chocolate',
    images: ['/images/C1.jpg'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 1299,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    countInStock: 54,
    numSales: 21,
    description:
      'Elegance meets indulgence with our Floral Designer Chocolate Cake. This exquisite cake features rich, moist chocolate layers, complemented by smooth chocolate frosting and adorned with delicate, handcrafted edible floral designs. A perfect choice to add a touch of beauty and sweetness to any celebration.',
    sizes: ['1.5-Kg'],
    shapes: ['Round'],

    reviews: [],
  },
  {
    name: 'Cute Panda Designer Cake',
    slug: toSlug('Cute Panda Designer Cake'),
    category: 'Designer-Cakes',
    flavour: 'Chocolate',
    images: ['/images/C2.jpg'],
    tags: ['featured'],
    isPublished: true,
    price: 825,
    listPrice: 0,
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 22,
    numSales: 54,
    description:
      'Bring a smile to any occasion with our Cute Panda Designer Cake. This adorable cake features soft, delicious layers of cake, covered with smooth frosting, and decorated with a playful panda design. Perfect for birthdays, baby showers, or any celebration that deserves a little extra charm and sweetness.',
    sizes: ['1/2-Kg'],
    shapes: ['Round'],

    reviews: [],
  },
  //Pinata Cakes
  {
    name: 'Gems Filled Pinata Cake - Truffle',
    slug: toSlug('Gems Filled Pinata Cake - Truffle'),
    category: 'Pinata-Cakes',
    flavour: 'Chocolate',
    images: ['/images/D1.jpg'],
    tags: ['best-seller'],
    isPublished: true,
    price: 899,
    listPrice: 0,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 23,
    numSales: 54,
    description:
      'Unwrap the fun with our Gems-Filled Chocolate Truffle Pinata Cake! Crafted with a rich chocolate shell, this pinata-style cake hides a surprise burst of colorful Gems inside. Beneath the shell lies a moist chocolate truffle cake layered with decadent frosting—perfect for celebrations full of excitement and sweetness!',
    sizes: ['1/2-Kg'],
    shapes: ['Round'],

    reviews: [],
  },
  //Jar Cakes
  {
    name: 'Blueberry Cream Jar Cake -Set of 2',
    slug: toSlug('Blueberry Cream Jar Cake -Set of 2'),
    category: 'Jar-Cakes',
    flavour: 'Blueberry',
    images: ['/images/E1.jpg'],
    tags: ['todays-deal'],
    isPublished: true,
    price: 359,
    listPrice: 0,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 24,
    numSales: 53,
    description:
      'Indulge in layers of delight with our Blueberry Cream Jar Cake. Packed in a convenient jar, this treat features fluffy vanilla sponge, luscious blueberry compote, and smooth whipped cream. A perfect blend of fruity freshness and creamy goodness in every spoonful!',
    sizes: [],
    shapes: [],

    reviews: [],
  },
  //Dry Cakes
  {
    name: 'Delightful Rums N Raisins Dry Cake 1kg',
    slug: toSlug('Delightful Rums N Raisins Dry Cake 1kg'),
    category: 'Dry-Cakes',
    flavour: 'Dry Fruits',
    images: ['/images/F1.jpg'],
    tags: ['new-arrival', 'featured'],
    isPublished: true,
    price: 599,
    listPrice: 0,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 25,
    numSales: 48,
    description:
      'Savor the rich, comforting taste of our Delightful Rums n Raisins Dry Cake. Made with premium ingredients, this moist and flavorful cake is infused with the warm essence of rum and studded with sweet raisins. Perfect for tea-time or festive gifting!',
    sizes: ['1-Kg'],
    shapes: ['Round'],

    reviews: [],
  },
  //2-tier Cakes
  {
    name: '50th Anniversary 2-tier 2kg Cake - Chocolate',
    slug: toSlug('50th Anniversary 2-tier 2kg Cake - Chocolate'),
    category: '2-tier-Cakes',
    flavour: 'Chocolate',
    images: ['/images/G1.jpg'],
    tags: ['best-seller', 'todays-deal'],
    isPublished: true,
    price: 2399,
    listPrice: 0,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 26,
    numSales: 48,
    description:
      'Celebrate 50 golden years of love with our 2-Tier Chocolate Cake (2kg). Elegantly designed for a grand occasion, this rich and decadent chocolate cake features moist layers filled with creamy frosting, beautifully adorned to mark a milestone of togetherness. A sweet tribute to a timeless journey!',
    sizes: ['2-Kg'],
    shapes: ['Round'],

    reviews: [],
  },
]

const data: Data = {
  products,
  headerMenus: [
    {
      name: "Today's Deal",
      href: '/search?tag=todays-deal',
    },
    {
      name: 'New Arrivals',
      href: '/search?tag=new-arrival',
    },
    {
      name: 'Featured Products',
      href: '/search?tag=featured',
    },
    {
      name: 'Best Sellers',
      href: '/search?tag=best-seller',
    },
    {
      name: 'Browsing History',
      href: '/#browsing-history',
    },
    {
      name: 'Customer Service',
      href: '/page/customer-service',
    },
    {
      name: 'About Us',
      href: '/page/about-us',
    },
    {
      name: 'Help',
      href: '/page/help',
    },
  ],
  carousels: [
    {
      title: 'Most Popular Shoes For Sale',
      buttonCaption: 'Shop Now',
      image: '/images/banner3.jpg',
      url: '/search?category=Shoes',
      isPublished: true,
    },
    {
      title: 'Best Sellers in T-Shirts',
      buttonCaption: 'Shop Now',
      image: '/images/banner1.jpg',
      url: '/search?category=T-Shirts',
      isPublished: true,
    },
    {
      title: 'Best Deals on Wrist Watches',
      buttonCaption: 'See More',
      image: '/images/banner2.jpg',
      url: '/search?category=Wrist Watches',
      isPublished: true,
    },
  ],
}

export default data
